version: "3"

services:
  node1:
    build: .
    container_name: node1
    networks:
      network1:
        ipv4_address: 10.23.1.10
    volumes:
      - ./sharedFiles:/app/sharedFiles  # Mount the sharedFiles directory
    environment:
      - JAVA_OPTS=-Dfile.encoding=UTF-8  # Optional: specify JVM options if needed

  node2:
    build: .
    container_name: node2
    networks:
      network1:
        ipv4_address: 10.23.1.20
      network2:
        ipv4_address: 10.23.2.20
    volumes:
      - ./sharedFiles:/app/sharedFiles  # Mount the sharedFiles directory
    environment:
      - JAVA_OPTS=-Dfile.encoding=UTF-8

  node3:
    build: .
    container_name: node3
    networks:
      network2:
        ipv4_address: 10.23.2.30
      network3:
        ipv4_address: 10.23.3.30
    volumes:
      - ./sharedFiles:/app/sharedFiles  # Mount the sharedFiles directory
    environment:
      - JAVA_OPTS=-Dfile.encoding=UTF-8

  node4:
    build: .
    container_name: node4
    networks:
      network3:
        ipv4_address: 10.23.3.40
      network4:
        ipv4_address: 10.23.4.40
    volumes:
      - ./sharedFiles:/app/sharedFiles  # Mount the sharedFiles directory
    environment:
      - JAVA_OPTS=-Dfile.encoding=UTF-8

  node5:
    build: .
    container_name: node5
    networks:
      network4:
        ipv4_address: 10.23.4.50
      network5:
        ipv4_address: 10.23.5.50
    volumes:
      - ./sharedFiles:/app/sharedFiles  # Mount the sharedFiles directory
    environment:
      - JAVA_OPTS=-Dfile.encoding=UTF-8

networks:
  network1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.23.1.0/24

  network2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.23.2.0/24

  network3:
    driver: bridge
    ipam:
      config:
        - subnet: 10.23.3.0/24

  network4:
    driver: bridge
    ipam:
      config:
        - subnet: 10.23.4.0/24

  network5:
    driver: bridge
    ipam:
      config:
        - subnet: 10.23.5.0/24
