version: '3.9'  # Updated version to avoid deprecated warning

services:
  node1:
    build: .
    container_name: node1
    networks:
      network1:
        ipv4_address: 10.23.1.10
    volumes:
      - ./sharedFiles/node1:/app/sharedFiles
      - /tmp/.X11-unix:/tmp/.X11-unix  # Mount X11 socket
    environment:
      - JAVA_OPTS=-Dfile.encoding=UTF-8
      - DISPLAY=${DISPLAY}  # Pass the DISPLAY environment variable

  node2:
    build: .
    container_name: node2
    networks:
      network2:
        ipv4_address: 10.23.2.20
      network1:
        ipv4_address: 10.23.1.20
    volumes:
      - ./sharedFiles/node2:/app/sharedFiles
      - /tmp/.X11-unix:/tmp/.X11-unix  # Mount X11 socket
    environment:
      - JAVA_OPTS=-Dfile.encoding=UTF-8
      - DISPLAY=${DISPLAY}  # Pass the DISPLAY environment variable

  node3:
    build: .
    container_name: node3
    networks:
      network3:
        ipv4_address: 10.23.3.30
      network2:
        ipv4_address: 10.23.2.30
    volumes:
      - ./sharedFiles/node3:/app/sharedFiles
      - /tmp/.X11-unix:/tmp/.X11-unix  # Mount X11 socket
    environment:
      - JAVA_OPTS=-Dfile.encoding=UTF-8
      - DISPLAY=${DISPLAY}  # Pass the DISPLAY environment variable

  node4:
    build: .
    container_name: node4
    networks:
      network4:
        ipv4_address: 10.23.4.40
      network3:
        ipv4_address: 10.23.3.40
    volumes:
      - ./sharedFiles/node4:/app/sharedFiles
      - /tmp/.X11-unix:/tmp/.X11-unix  # Mount X11 socket
    environment:
      - JAVA_OPTS=-Dfile.encoding=UTF-8
      - DISPLAY=${DISPLAY}  # Pass the DISPLAY environment variable

  node5:
    build: .
    container_name: node5
    networks:
      network5:
        ipv4_address: 10.23.5.50
    volumes:
      - ./sharedFiles/node5:/app/sharedFiles
      - /tmp/.X11-unix:/tmp/.X11-unix  # Mount X11 socket
    environment:
      - JAVA_OPTS=-Dfile.encoding=UTF-8
      - DISPLAY=${DISPLAY}  # Pass the DISPLAY environment variable

networks:
  network1:
    driver: bridge
    ipam:
      config:
        - subnet: 10.23.1.0/24

  network2:
    driver: bridge
    ipam:
      config:
        - subnet: 10.23.2.0/24

  network3:
    driver: bridge
    ipam:
      config:
        - subnet: 10.23.3.0/24

  network4:
    driver: bridge
    ipam:
      config:
        - subnet: 10.23.4.0/24

  network5:
    driver: bridge
    ipam:
      config:
        - subnet: 10.23.5.0/24
